// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'product.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_Product _$_$_ProductFromJson(Map<String, dynamic> json) {
  return _$_Product(
    id: json['id'] as String,
    name: json['name'] as String,
    category: json['category'] as String,
    weight: (json['weight'] as num)?.toDouble(),
    barcode: json['barcode'] as int,
    kcal: json['kcal'] as int,
    carbohydrates: (json['carbohydrates'] as num)?.toDouble(),
    proteins: (json['proteins'] as num)?.toDouble(),
    fats: (json['fats'] as num)?.toDouble(),
    sugars: (json['sugars'] as num)?.toDouble(),
    salt: (json['salt'] as num)?.toDouble(),
    saturated: (json['saturated'] as num)?.toDouble(),
    monounsaturated: (json['monounsaturated'] as num)?.toDouble(),
    poliunsaturated: (json['poliunsaturated'] as num)?.toDouble(),
    omega3: (json['omega3'] as num)?.toDouble(),
    omega6: (json['omega6'] as num)?.toDouble(),
    ala: (json['ala'] as num)?.toDouble(),
    epa: (json['epa'] as num)?.toDouble(),
    dha: (json['dha'] as num)?.toDouble(),
    fibre: (json['fibre'] as num)?.toDouble(),
    cholesterol: (json['cholesterol'] as num)?.toDouble(),
    caffeine: (json['caffeine'] as num)?.toDouble(),
    vitaminA: (json['vitaminA'] as num)?.toDouble(),
    vitaminB1: (json['vitaminB1'] as num)?.toDouble(),
    vitaminB2: (json['vitaminB2'] as num)?.toDouble(),
    vitaminB3: (json['vitaminB3'] as num)?.toDouble(),
    vitaminB4: (json['vitaminB4'] as num)?.toDouble(),
    vitaminB5: (json['vitaminB5'] as num)?.toDouble(),
    vitaminB6: (json['vitaminB6'] as num)?.toDouble(),
    vitaminB7: (json['vitaminB7'] as num)?.toDouble(),
    vitaminB9: (json['vitaminB9'] as num)?.toDouble(),
    vitaminB12: (json['vitaminB12'] as num)?.toDouble(),
    vitaminC: (json['vitaminC'] as num)?.toDouble(),
    vitaminD: (json['vitaminD'] as num)?.toDouble(),
    vitaminE: (json['vitaminE'] as num)?.toDouble(),
    vitaminK: (json['vitaminK'] as num)?.toDouble(),
    sodium: (json['sodium'] as num)?.toDouble(),
    potassium: (json['potassium'] as num)?.toDouble(),
    calcium: (json['calcium'] as num)?.toDouble(),
    magnesium: (json['magnesium'] as num)?.toDouble(),
    phosphorous: (json['phosphorous'] as num)?.toDouble(),
    iron: (json['iron'] as num)?.toDouble(),
    copper: (json['copper'] as num)?.toDouble(),
    zinc: (json['zinc'] as num)?.toDouble(),
    fluorine: (json['fluorine'] as num)?.toDouble(),
    selenium: (json['selenium'] as num)?.toDouble(),
    iodine: (json['iodine'] as num)?.toDouble(),
  );
}

Map<String, dynamic> _$_$_ProductToJson(_$_Product instance) =>
    <String, dynamic>{
      'id': instance.id,
      'name': instance.name,
      'category': instance.category,
      'weight': instance.weight,
      'barcode': instance.barcode,
      'kcal': instance.kcal,
      'carbohydrates': instance.carbohydrates,
      'proteins': instance.proteins,
      'fats': instance.fats,
      'sugars': instance.sugars,
      'salt': instance.salt,
      'saturated': instance.saturated,
      'monounsaturated': instance.monounsaturated,
      'poliunsaturated': instance.poliunsaturated,
      'omega3': instance.omega3,
      'omega6': instance.omega6,
      'ala': instance.ala,
      'epa': instance.epa,
      'dha': instance.dha,
      'fibre': instance.fibre,
      'cholesterol': instance.cholesterol,
      'caffeine': instance.caffeine,
      'vitaminA': instance.vitaminA,
      'vitaminB1': instance.vitaminB1,
      'vitaminB2': instance.vitaminB2,
      'vitaminB3': instance.vitaminB3,
      'vitaminB4': instance.vitaminB4,
      'vitaminB5': instance.vitaminB5,
      'vitaminB6': instance.vitaminB6,
      'vitaminB7': instance.vitaminB7,
      'vitaminB9': instance.vitaminB9,
      'vitaminB12': instance.vitaminB12,
      'vitaminC': instance.vitaminC,
      'vitaminD': instance.vitaminD,
      'vitaminE': instance.vitaminE,
      'vitaminK': instance.vitaminK,
      'sodium': instance.sodium,
      'potassium': instance.potassium,
      'calcium': instance.calcium,
      'magnesium': instance.magnesium,
      'phosphorous': instance.phosphorous,
      'iron': instance.iron,
      'copper': instance.copper,
      'zinc': instance.zinc,
      'fluorine': instance.fluorine,
      'selenium': instance.selenium,
      'iodine': instance.iodine,
    };
